apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: frontend-dev
        name: myapp
        imagePullPolicy: Never #makes it so it looks at your local registry
        # imagePullPolicy: IfNotPresent   
        ports:
        - containerPort: 8080
        # 0.0.0.0:8080->80/tcp add this here...
      # imagePullSecrets:
      #   - name: docker-secret
